### ISSUE TITLE
scrolling (horizontal and vertical) with micro stuttering 

### ISSUE THREAD

**Issue by onaryc** [rsn8887/uae4all2#5]
I have tested uae4all with a lot of screen size/ratio/refresh rate configuration. I manage to obtain the complete screen but the scrolling is never completely smooth (even if the game is running at 100%). There are micro stuttering which i also obtain with fs-uae mainly due to rendering a 50hz game on a 60hz screen (i manage to obtain a completely smooth scrolling on PC by adding 50hz video mode through the driver).

Is there a way to obtain a 50hz refresh rate with the vita video mode? or is there no way to achieve a 50hz smooth scrolling with the vita?  

Note : the 60hz option does not seem to work, the music and the game speed remains correct (it should not be)

**Comment by onaryc** [comment]
i continue to test the settings, this time on my pstv and notice the following things : 
* in fact the 60hz option works in 2 cases : when the emulator is reset (r trigger) with the option set to 60hz and the sound is active (if one try to set to 50hz during emulation it does not seems to work) or if the option is set to 50hz and the sound is deactivate (during emulation also)
* with the above observation, i have the impression that 50hz is achieved through audio synchronization and not through video mode. I don't know if there is a way to activate a 50hz mode on vita, but it will be golden :)

**Comment by rsn8887** [comment]
I am afraid it is not possible to fix the micro stuttering in 50 Hz mode. It is a hardware limitation. The only way to get rid of it would be to use a display with 50 Hz refresh rate and output a 50 Hz screen mode. But that is not possible on Vita or VitaTV: the builtin Vita screen is fixed at 60 Hz, and the HDMI output modes on VitaTV are also fixed at 60 Hz. 

As you found out, the scrolling is much smoother when switching the emulator to emulate a NTSC/60 HZ Amiga. However, that is not a viable solution, because Amiga games run way too fast in this mode. Even the sound plays too fast in this mode. The same happens on a real Amiga if you switch it to NTSC. The games were all programmed with 50 Hz/PAL speed in mind.

**Comment by onaryc** [comment]
arrf that's too bad they fix the hdmi output to 60hz. Thanks for the response (and your work on this emulator).
